kafka实现添加
ecodeclub/mq-api pull request #1
Opened 2023-10-14 14:12 UTC by juniaoshaonian

1. 修改了api 增加了分区，消费组。生产者增加了指定分区消费
2. 添加了kafka的实现
3. 内存的实现等过几天修改

2023-10-15 02:05 UTC, longyue0521 requested changes

2023-10-15 02:05 UTC, longyue0521 commented on type.go
> +	Consumer(topic string, id string) (Consumer, error)
id命名不具有描述性,缺少注释

2023-10-15 02:05 UTC, longyue0521 commented on type.go
>  	ConsumeMsgCh(ctx context.Context) (<-chan *Message, error)
ConsumeChan, 返回值<-chan *Message已携带msg语义

2023-10-15 02:05 UTC, longyue0521 commented on type.go
> +	ProduceWithPartition(ctx context.Context, m *Message, partition int32) (*ProducerResult, error)
partition概念上有歧义,这里应该指的是分区的索引号

2023-10-15 02:05 UTC, longyue0521 commented on mqerr/error.go
> +	ErrKafkaUnKnowType = errors.New("未知的kafka消息类型")
用户断言error的时候,不知道也不该知道底层的具体实现,改为`ErrUnKnowMessageType = errrors.New("未知的消息类型")`与`ErrTopicNotFound`对齐

kafka实现中使用`fmt.Errorf("kafka: %w",ErrUnKnowMessageType)`

2023-10-15 02:05 UTC, longyue0521 commented on type.go
> +	Offset int64
1. value, key, header,Topic缺少描述
2. Partition有歧义,此处指定的是某个分区的索引号 改为PartitionIndex?

2023-10-15 02:05 UTC, longyue0521 commented on memory/consumer.go
> +package memory
此次PR是描述Kafka实现的,memory相关的内容实现也不完善,等实现好后另提PR,去掉memory目录相关内容避免对review造成干扰

2023-10-15 02:05 UTC, longyue0521 commented on kafka/producer.go
> +}
common/func.go也有这个方法啊

2023-10-15 02:05 UTC, longyue0521 commented on kafka/producer.go
> +	return &mq.ProducerResult{}, nil
抽取方法`produce(ctx, kafka.Message)`并使用该方法重构`Produce`及`ProduceWithPartition`消除重复代码

2023-10-15 02:05 UTC, longyue0521 commented on kafka/producer.go
> +type CustomProducer struct {
Producer

2023-10-15 02:25 UTC, longyue0521 requested changes

2023-10-15 02:25 UTC, longyue0521 commented on kafka/mq.go
> +func NewCustomMq(brokers []string) (*CustomMQ, error) {
`kafka.NewMQ(xxx)`

2023-10-15 02:25 UTC, longyue0521 commented on e2e/kafka_test.go
> +	suite.Run(t, NewKafkaSuite([]string{"127.0.0.1:9092"}))
func TestKafkaMQ

2023-10-15 02:25 UTC, longyue0521 commented on e2e/kafka_test.go
> +	suite.Run(t, NewKafkaSuite([]string{"127.0.0.1:9092"}))
添加Clear方法到MQ抽象, 去除特定的TestSuite

2023-10-15 02:25 UTC, longyue0521 commented on kafka/consumer.go
> +type CustomConsumer struct {
Consumer

2023-10-15 03:13 UTC, longyue0521 requested changes

2023-10-15 03:13 UTC, longyue0521 commented on e2e/base_test.go
> +func (b *BaseSuite) TestMSMQConsumer_DiffGroup() {
TestMQConsumer_ConsumerGroup

2023-10-15 03:13 UTC, longyue0521 commented on e2e/base_test.go
> +			consumerFunc: func(c mq.Consumer) []*mq.Message {
consumeFunc

2023-10-15 03:13 UTC, longyue0521 commented on e2e/base_test.go
> +	InitMq() mq.MQ
Init

2023-10-15 03:13 UTC, longyue0521 commented on type.go
> +	Topic(ctx context.Context, topic string, partition int) error
partitions 表示分区数

2023-10-15 03:13 UTC, longyue0521 commented on e2e/base_test.go
> +func (b *BaseSuite) TestMSMQConsumer_PartitionSort() {
TestMQConsumer_OrderOfMessagesWithinAPartition

2023-10-15 03:13 UTC, longyue0521 commented on e2e/base_test.go
> +func (b *BaseSuite) TestMSMQProducer_ProduceWithPartition() {
TestMQProducer_ProduceWithSpecifiedPartitionID

2023-10-15 04:00 UTC, longyue0521 requested changes

2023-10-15 04:00 UTC, longyue0521 commented on kafka/mq.go
> +type CustomMQ struct {
MQ

2023-10-15 04:00 UTC, longyue0521 commented on docker-compose-3rd.yaml
> +    image: 'bitnami/kafka:3.3.1'
使用最新稳定版本

2023-10-15 04:00 UTC, longyue0521 commented on e2e/base_test.go
> +type BaseSuite struct {
TestSuite

2023-10-15 04:00 UTC, longyue0521 commented on e2e/base_test.go
> +			name:       "多个消费组,多个消费组并行消费",
多个消费组订阅同一个Topic,消费组之间可以重复消费消息

2023-10-15 04:00 UTC, longyue0521 commented on e2e/base_test.go
> +			name:       "一个消费组竞争消费",
同一消费者组内,各个消费者竞争消费消息

2023-10-15 04:00 UTC, longyue0521 commented on e2e/base_test.go
> +			wg.Wait()
mqm.Close()会导致consumerFunc内的for...range中断,从而导致消费者go协程退出,这样wg.Wait好像就没有作用了

2023-10-15 04:00 UTC, longyue0521 commented on kafka/consumer.go
> +func (c *CustomConsumer) GetMsgFromKafka() {
改为包内可见

2023-10-15 04:00 UTC, longyue0521 commented on kafka/consumer.go
> +		//err = c.consumer.Close()
在`GetMsgFromKafka `中有如下代码:
```go
if c.consumer.IsClosed() {
    return
}
```
这里是否要主动关闭`c. consumer`

2023-10-15 04:00 UTC, longyue0521 commented on kafka/consumer.go
> +func (c *CustomConsumer) ConsumerSeek(partition int64, offset int64) error {
partitionID

2023-10-15 04:00 UTC, longyue0521 commented on kafka/consumer.go
> +	tp := kafka.TopicPartition{
把官方kafka的包名重命名以示区分,比如officialkafka

2023-10-15 04:37 UTC, longyue0521 requested changes

2023-10-15 04:37 UTC, longyue0521 commented on kafka/consumer.go
> +	select {
缺少一个case:

case <-closeCh:
    return nil, 消费者连接已关闭

2023-10-15 04:37 UTC, longyue0521 commented on kafka/consumer.go
> +	defer c.consumer.Close()
1. GetMsgFromKafka 改为包内可见
2. defer c.consumer.Close() + close(c.msgCh)

2023-10-15 04:37 UTC, longyue0521 commented on kafka/consumer.go
> +			}
去掉

2023-10-15 04:53 UTC, longyue0521 requested changes

2023-10-15 04:53 UTC, longyue0521 commented on kafka/mq.go
> +func (m *CustomMQ) Topic(ctx context.Context, name string, partition int) error {
1. partitions/numPartitions
2. m.adminClient.Close()后或者说调用`(m *CustomMQ) Close() error`后再调用该方法会发生什么?编写测试用例覆盖

2023-10-15 04:53 UTC, longyue0521 commented on kafka/mq.go
> +func (m *CustomMQ) Producer(topic string) (mq.Producer, error) {
m.adminClient.Close()后或者说调用`(m *CustomMQ) Close() error`后再调用该方法会发生什么?编写测试用例覆盖

2023-10-15 04:53 UTC, longyue0521 commented on kafka/mq.go
> +func (m *CustomMQ) Consumer(topic string, id string) (mq.Consumer, error) {
1. id问题
2. m.adminClient.Close()后或者说调用`(m *CustomMQ) Close() error`后再调用该方法会发生什么?编写测试用例覆盖

2023-10-15 04:53 UTC, longyue0521 commented on kafka/producer.go
> +
1. 缺少type.go中定义的Close()方法
2. 未处理调用Close方法后,再调用Produce、ProduceWithPartition会发生什么? 编写测试用例覆盖

2023-10-15 10:01 UTC, juniaoshaonian commented on kafka/consumer.go
> +		//err = c.consumer.Close()
不行得退出那个 getMsgFromKafka 的时候关闭，否则被引用到就报错

2023-10-15 10:22 UTC, longyue0521 commented on kafka/consumer.go
> +		//err = c.consumer.Close()
那就要注释掉getMsgFromKafka中的上述代码了, 因为getMsgFromKafka你是知道关闭时机的.

2023-10-16 02:16 UTC, longyue0521 requested changes

2023-10-16 02:16 UTC, longyue0521 commented on type.go
> +	// Topic 创建topic并制定topic的分区数，partitions 表示分区数。分区从0开始编号 例如分区数为4，那么分区号就是0-3
1. 缺少对MQ interface的顶层注释, 包括MQ是否为并发安全
2. Close()多次调用的预期结果未描述
3. 注释: groupID为消费组ID
4. 添加一个`Ping(ctx context.Context) error`方法用于确定当前MQ已经启动可用.

2023-10-16 02:16 UTC, longyue0521 commented on type.go
>  	Consume(ctx context.Context) (*Message, error)
1. 缺少对Consumer interface的顶层注释, 包括Consumer是否为并发安全的
2. Close()多次调用的预期结果未描述

2023-10-16 02:16 UTC, longyue0521 commented on type.go
> +	// Produce 不指定分区发送消息，具体消息在哪个分区看具体实现
1. 缺少对Producer interface的顶层注释, 包括Producer是否为并发安全的
2. Close()多次调用的预期结果未描述

2023-10-16 02:16 UTC, longyue0521 commented on mqerr/error.go
> +	ErrMqIsClosed        = errors.New("mq已经关闭")
ErrMQIsClosed

2023-10-16 02:16 UTC, longyue0521 commented on type.go
> +	Key   []byte
这个注释让人觉得Value和Key是消息本体.分别注释一下value是什么语义?业务消息,是否可以省略等, key是什么语义?是否可以省略等.

2023-10-16 02:16 UTC, longyue0521 commented on common/func.go
当前文件中的两个函数与kafka的具体实现直接/强相关,而并非各种具体MQ实现通用的函数,故将本文件整体移动到kafka目录下,并删除common目录

2023-10-16 02:16 UTC, longyue0521 commented on kafka/consumer.go
> +	id    string
id是什么ID?用来干什么?

2023-10-16 02:16 UTC, longyue0521 commented on kafka/consumer.go
> +}
改写for循环,去掉外层的select,只保留default内部的内容即可

2023-10-16 02:16 UTC, longyue0521 commented on kafka/consumer.go
> +	if c.closed {
1. 使用下方isClosed, 补充缺失的并发测试,覆盖当前场景
2. 检查ctx.Err, 补充缺失的测试,覆盖当前场景

2023-10-16 02:16 UTC, longyue0521 commented on kafka/consumer.go
> +	if c.closed {
1. 使用下方isClosed, 补充缺失的并发测试,覆盖当前场景
2. c.isClosed()见producer.go问题描述

2023-10-16 02:16 UTC, longyue0521 commented on kafka/consumer.go
> +		return nil, mqerr.ErrConsumerIsClosed
mqerr.ErrConsumerIsClosed 要不要wrap一下?

2023-10-16 02:16 UTC, longyue0521 commented on kafka/consumer.go
> +			m, err := c.consumer.ReadMessage(100 * time.Millisecond)
100 * time.Millisecond 抽取为包级别常量

2023-10-16 03:19 UTC, longyue0521 requested changes

2023-10-16 03:19 UTC, longyue0521 commented on kafka/producer.go
> +	if p.isClosed() {
这种写法的问题在于,当控制流刚刚从p.isClosed()出来,p.Close()被并发的协程调用了,当前控制流会继续走到`p.produce(ctx, kafkaMsg)`

确认一下
1. `p.producer`是否为并发安全的
2. 如果是,可以去掉`p.isClosed()方法` 然后使用`err := p.producer.Produce(msg, deliveryChan)`中err来判定是否为close
3. 如果不是, 将`p.isClosed()`中的内容展开到`Produce`和`ProduceWithPartition`中变为并发安全的

MQ、Consumer中的isClosed()问题处理同上

2023-10-16 03:19 UTC, longyue0521 commented on type.go
> +	ClearTopic(ctx context.Context, topics []string) error
改为DeleteTopics

2023-10-16 03:19 UTC, longyue0521 commented on kafka/mq.go
> +	}
1. id => groupID
2. m.isClosed()问题,见producer.go问题描述

2023-10-16 03:43 UTC, longyue0521 requested changes

2023-10-16 03:43 UTC, longyue0521 commented on e2e/base_test.go
> +func NewBaseSuite(mqCreator MqCreator) *TestSuite {
1. NewTestSuit
2. 在TestSuite中保存一个mq.MQ对象即可,去掉MqCreator这个抽象,因为你下方的一系列操作都是就是调用kafka.NewMQ

2023-10-16 03:43 UTC, longyue0521 commented on e2e/base_test.go
> +}
使用mq.MQ中新增的Ping(ctx)接口前确保消息队列已启动

2023-10-16 03:43 UTC, longyue0521 commented on e2e/base_test.go
> +}
1. 重命名为`TestKafka`
2. 移动到`kafka_test.go`中

2023-10-16 03:43 UTC, longyue0521 commented on e2e/kafka_test.go
```go
func TestKafka(t *testing.T) { 
       // 原来的Init操作 直接展开在这里就可以了
        q, err := kafka.NewMQ([]string{"127.0.0.1:9092"})
        require.NoError(t, err)
	suite.Run(t, NewTestSuite(q))
}
```

2023-10-16 14:32 UTC, juniaoshaonian commented on kafka/consumer.go
> +}
这个有一种情况就是我有可能这段时间我没有数据产生，我会一直读取超时。但是这时候我关闭了closeC。这会导致我在这段时间内无法退出循环。

2023-10-16 15:56 UTC, juniaoshaonian commented on kafka/consumer.go
> +	if c.closed {
这个如果使用isClosed方法是不是不存在并发不安全的情况了因为下面都是channel和私有变量

2023-10-17 02:11 UTC, longyue0521 requested changes

2023-10-17 02:11 UTC, longyue0521 commented on kafka/consumer.go
> +	"github.com/confluentinc/confluent-kafka-go/v2/kafka"
此包底层依赖于cgo,调研下列kafka纯go客户端:
1. https://github.com/twmb/franz-go
2. https://github.com/segmentio/kafka-go
选择其一进行替换

2023-10-17 05:51 UTC, longyue0521 commented
@juniaoshaonian 拉取最新代码 处理冲突 解决各个conversation中的问题 然后resolve conversation 再发送review request

2023-10-18 13:11 UTC, longyue0521 commented
@juniaoshaonian  
1. 把上方的对话一个一个resovle掉,再次确认当前已将问题修复
2. 拉取最新代码 处理冲突 使用 rebase 将你PR中CI相关的东西去掉
3. 先在本地执行make setup, 再把下方CI检查出错的地方修一下

2023-10-21 02:04 UTC, longyue0521 commented
先合并,我来调整

2023-10-21 02:04 UTC, merged